export const mockCampaigns = [
/*data format explanation:
{
         coordinates: [51.943259, 4.143100], //centre coordinates of location
         name: "Europoort Rotterdam", //Location/campaign name
         exinfoHTML: "The biggest port in Europe....", // explanatory/additional info for the campaign
         infoHTML: "CO2 Decrease", //short goal description
         kpis: [{ name: "Decrease CO2", target: "75%" }], //end goal
         availableMenus: ["Grid", "Solar", "Bioenergy", "Energy Efficiency","Batteries","Hydroelectric"], //available menus to use in simulation
         budget:5414100, //starting budget
         colors:{   
           primary:"#78cc7e",
           secondary:"#418745" //colors to use in campaign
         }
       },
*/
    {
         coordinates: [51.943259, 4.143100],
         name: "Europoort Rotterdam",budget:5414100,
         exinfoHTML: "The biggest port in Europe, Rotterdam is a major contributor to the Dutch CO2 emissions. How green can you make it?",
         infoHTML: "CO2 Decrease",
         kpis: [{ name: "Decrease CO2", target: "75%" }],
         availableMenus: ["Grid", "Solar", "Bioenergy", "Energy Efficiency","Batteries","Hydroelectric"],
         generalKPIs: {
           "AVG Grid Capacity": "AVG grid capacity",
           "Solar Generation": "Generation"
         },
         colors:{
           primary:"#78cc7e",
           secondary:"#418745"
         }
       },
       
    {
      coordinates: [52.3259, 5.43100],
      name: "Zenmo Zero",budget:5414100,
      exinfoHTML: "Zenmo Zero is an energy transition simulation game based on cutting edge digital twin simulation technologies. Learn how different energy transition technologies work",
      infoHTML: "What is it?",
      kpis: [],
      availableMenus: ["Grid", "Solar", "Bioenergy", "Energy Efficiency","Batteries","Hydroelectric"],
      generalKPIs: {
        "AVG Grid Capacity": "AVG grid capacity",
        "Solar Generation": "Generation"
      },
      colors:{
        primary:"#78cc7e",
        secondary:"#418745"
      }
    },
       {
         coordinates: [52.357576, 6.214733],
         name: "Broekland",budget:400000,
         exinfoHTML: "What do you do with the farmland that has been overused and needs some time to recover? Put some solar panels there! About 85% of the electricity consumed here could be generated by solar.",
         infoHTML: "Solar Generation",
         kpis: [{ name: "Solar Consumption", target: "80%" }],
         availableMenus: ["Grid", "Solar"],
         generalKPIs: {
           "AVG Grid Capacity": "AVG grid capacity",
           "Solar Generation": "Generation"
         },
         colors:{
           primary:"#c8cd68",
           secondary:"#757b2d"
         }
       },
       {
         coordinates: [51.5299716003893, 3.5615900475857014],
         name: "Grijpskerke",
         budget:2021014,
         exinfoHTML: "The province of Zeeland has good potential for wind power generation. Throughout the campaign, you will have to generate 20% more power than consumed, 95% of it being primarily generated by wind.",
         infoHTML: "Windpower",
         kpis: [
           { name: "Generated Power", target: "20% Over" },
           { name: "Total Wind Generation", target: "95%" }
         ],
         availableMenus: ["Grid", "Wind"],
         generalKPIs: {
           "AVG Grid Capacity": "AVG grid capacity",
           "Wind generators": "Wind generators"
         },
         colors:{
           primary:"#8aa6d9",
           secondary:"#454e5e"
         }
       }
     ];